// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type BaseRequest struct {
	Id   string `json:"id"`   // 主键
	Name string `json:"name"` // 名称
}

type BaseResponse struct {
	Result string `json:"result"` // 结果
}

type URLRequest struct {
	URL string `json:"url"` // URL链接
}

type URLResponse struct {
	Tag         []string `json:"tag"`         // 标签
	Title       string   `json:"title"`       // 标题
	Description string   `json:"description"` // 描述
	Link        string   `json:"link"`        // 链接
}
