// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type BaseRequest struct {
	Id   string `json:"id"`   // 主键
	Name string `json:"name"` // 名称
}

type BaseResponse struct {
	Result string `json:"result"` // 结果
}

type CancelTaskRequest struct {
	Tid string `json:"tid"` // 任务唯一标识
}

type CreateAiResourceRequest struct {
	URL string `json:"url"` // URL链接
}

type CreateBatchTagRequest struct {
	Tags []CreateTagRequest `json:"tags"`
}

type CreateBatchTagResponse struct {
	CreatedTotal       int64               `json:"created_total"`        // 创建总数
	ExistedTotal       int64               `json:"existed_total"`        // 已存在总数
	CreateTagResponses []CreateTagResponse `json:"create_tag_responses"` // 结果
}

type CreateModelRequest struct {
	BaseUrl       string   `json:"base_url"`        // 基础URL
	Config        string   `json:"config"`          // 配置信息
	Type          string   `json:"type"`            // 类型
	ModelName     string   `json:"model_name"`      // 模型名称
	ModelRealName string   `json:"model_real_name"` // 模型真实名称
	Status        string   `json:"status"`          // 状态
	Tag           []string `json:"tag"`             // 标签
}

type CreateResourceRequest struct {
	URL     string   `json:"url"`      // URL链接
	Title   string   `json:"title"`    // 标题
	Content string   `json:"content"`  // 内容
	Type    string   `json:"type"`     // 类型
	TagUids []string `json:"tag_uids"` // 标签ID
}

type CreateTagRequest struct {
	Name        string `json:"name"`        // 标签名称
	Description string `json:"description"` // 标签描述
	Color       string `json:"color"`       // 标签颜色
	Icon        string `json:"icon"`        // 标签图标
}

type CreateTagResponse struct {
	Id          int64  `json:"id"`          // 主键ID
	Uid         string `json:"uid"`         // 标签唯一标识
	Name        string `json:"name"`        // 标签名称
	Description string `json:"description"` // 标签描述
	Color       string `json:"color"`       // 标签颜色
	Icon        string `json:"icon"`        // 标签图标
	CreatedAt   string `json:"created_at"`  // 创建时间
	UpdatedAt   string `json:"updated_at"`  // 更新时间
}

type CreateTaskRequest struct {
	Name         string `json:"name"`          // 任务名称
	Types        string `json:"types"`         // 任务类型
	Params       string `json:"params"`        // 任务参数
	TotalSteps   int64  `json:"total_steps"`   // 总步骤
	CurrentState string `json:"current_state"` // 当前状态机
}

type CreateTaskResponse struct {
	Id           int64  `json:"id"`            // 主键ID
	Tid          string `json:"tid"`           // 任务唯一标识
	Name         string `json:"name"`          // 任务名称
	Types        string `json:"types"`         // 任务类型
	Status       string `json:"status"`        // 任务状态
	CurrentState string `json:"current_state"` // 当前状态机
	TotalSteps   int64  `json:"total_steps"`   // 总步骤
	CurrentStep  int64  `json:"current_step"`  // 当前步骤
	RetryCount   int64  `json:"retry_count"`   // 重试次数
	Params       string `json:"params"`        // 任务参数
	Result       string `json:"result"`        // 任务结果
	Duration     int64  `json:"duration"`      // 任务耗时
	Error        string `json:"error"`         // 任务错误
	Extend       string `json:"extend"`        // 扩展字段
	CreatedAt    string `json:"created_at"`    // 创建时间
	UpdatedAt    string `json:"updated_at"`    // 更新时间
}

type DeleteModelRequest struct {
	Id int64 `form:"id"` // 主键
}

type DeleteResourceRequest struct {
	Id int64 `form:"id"` // 主键
}

type DeleteTagRequest struct {
	Uid string `json:"uid"` // 标签唯一标识
}

type DeleteTagResponse struct {
	Result string `json:"result"` // 结果
}

type DeleteTaskRequest struct {
	Tid string `json:"tid"` // 任务唯一标识
}

type DeleteTaskResponse struct {
	Result string `json:"result"` // 结果
}

type GetModelRequest struct {
	Id int64 `form:"id"` // 主键
}

type GetResourceRequest struct {
	Id int64 `form:"id"` // 主键
}

type GetTagRequest struct {
	Uid string `json:"uid"` // 标签唯一标识
}

type GetTaskRequest struct {
	Tid string `json:"tid"` // 任务唯一标识
}

type GetTaskVisualizationRequest struct {
	Tid string `form:"tid"` // 任务唯一标识
}

type IdentifyResourceRequest struct {
	URL string `json:"url"` // URL链接,多个逗号分隔
}

type IdentifyResourceResponse struct {
	Urls []string `json:"urls"` // 任务ID列表
}

type ListModelRequest struct {
	Page     int64    `json:"page"`             // 页码
	PageSize int64    `json:"page_size"`        // 每页数量
	Type     string   `json:"type,optional"`    // 类型（可选）
	Status   string   `json:"status,optional"`  // 状态（可选）
	Tag      []string `json:"tag,optional"`     // 标签（可选）
	Keyword  string   `json:"keyword,optional"` // 关键词（可选）
}

type ListModelResponse struct {
	Total  int64   `json:"total"`  // 总数
	Models []Model `json:"models"` // 模型列表
}

type ListResourceRequest struct {
	Page     int64    `json:"page"`              // 页码
	PageSize int64    `json:"page_size"`         // 每页数量
	Type     string   `json:"type,optional"`     // 类型（可选）
	TagUids  []string `json:"tag_uids,optional"` // 标签（可选）
	Keyword  string   `json:"keyword,optional"`  // 关键词（可选）
}

type ListResourceResponse struct {
	Total     int64      `json:"total"`     // 总数
	Resources []Resource `json:"resources"` // 资源列表
}

type ListTagRequest struct {
	Page     int64  `form:"page,default=1"`       // 页码
	PageSize int64  `form:"page_size,default=10"` // 每页数量
	Name     string `form:"name,optional"`        // 标签名称（模糊查询）
}

type ListTagResponse struct {
	Total int64         `json:"total"` // 总数
	List  []TagResponse `json:"list"`  // 标签列表
}

type ListTaskRequest struct {
	Page     int64  `form:"page,default=1"`       // 页码
	PageSize int64  `form:"page_size,default=10"` // 每页数量
	Name     string `form:"name,optional"`        // 任务名称（模糊查询）
	Types    string `form:"types,optional"`       // 任务类型
	Status   string `form:"status,optional"`      // 任务状态
}

type ListTaskResponse struct {
	Total int64          `json:"total"` // 总数
	List  []TaskResponse `json:"list"`  // 任务列表
}

type Model struct {
	Id            int64    `json:"id"`              // 主键
	BaseUrl       string   `json:"base_url"`        // 基础URL
	Config        string   `json:"config"`          // 配置信息
	Type          string   `json:"type"`            // 类型
	ModelName     string   `json:"model_name"`      // 模型名称
	ModelRealName string   `json:"model_real_name"` // 模型真实名称
	Status        string   `json:"status"`          // 状态
	Tag           []string `json:"tag"`             // 标签
	CreatedAt     string   `json:"created_at"`      // 创建时间
	UpdatedAt     string   `json:"updated_at"`      // 更新时间
}

type PauseTaskRequest struct {
	Tid string `json:"tid"` // 任务唯一标识
}

type Resource struct {
	Id        int64    `json:"id"`         // 主键
	URL       string   `json:"url"`        // URL链接
	Title     string   `json:"title"`      // 标题
	Content   string   `json:"content"`    // 内容
	Type      string   `json:"type"`       // 类型
	Tags      []string `json:"tags"`       // 标签
	TagUids   []string `json:"tag_uids"`   // 标签ID
	CreatedAt string   `json:"created_at"` // 创建时间
	UpdatedAt string   `json:"updated_at"` // 更新时间
}

type ResumeTaskRequest struct {
	Tid string `json:"tid"` // 任务唯一标识
}

type RetryTaskRequest struct {
	Tid string `json:"tid"` // 任务唯一标识
}

type TagResponse struct {
	Uid         string `json:"uid"`         // 标签唯一标识
	Name        string `json:"name"`        // 标签名称
	Description string `json:"description"` // 标签描述
	Color       string `json:"color"`       // 标签颜色
	Icon        string `json:"icon"`        // 标签图标
	CreatedAt   string `json:"created_at"`  // 创建时间
	UpdatedAt   string `json:"updated_at"`  // 更新时间
}

type TaskOperationResponse struct {
	Result string `json:"result"` // 操作结果
}

type TaskPlanDetail struct {
	Pid       string `json:"pid"`        // 任务计划唯一标识
	Name      string `json:"name"`       // 任务计划名称
	Index     int64  `json:"index"`      // 任务计划索引
	Status    string `json:"status"`     // 任务状态
	Params    string `json:"params"`     // 任务参数
	Result    string `json:"result"`     // 任务结果
	Duration  int64  `json:"duration"`   // 任务耗时
	Error     string `json:"error"`      // 任务错误
	CreatedAt string `json:"created_at"` // 创建时间
	UpdatedAt string `json:"updated_at"` // 更新时间
}

type TaskResponse struct {
	Tid          string `json:"tid"`           // 任务唯一标识
	Name         string `json:"name"`          // 任务名称
	Types        string `json:"types"`         // 任务类型
	Status       string `json:"status"`        // 任务状态
	CurrentState string `json:"current_state"` // 当前状态机
	TotalSteps   int64  `json:"total_steps"`   // 总步骤
	CurrentStep  int64  `json:"current_step"`  // 当前步骤
	RetryCount   int64  `json:"retry_count"`   // 重试次数
	Params       string `json:"params"`        // 任务参数
	Result       string `json:"result"`        // 任务结果
	Duration     int64  `json:"duration"`      // 任务耗时
	Error        string `json:"error"`         // 任务错误
	Extend       string `json:"extend"`        // 扩展字段
	CreatedAt    string `json:"created_at"`    // 创建时间
	UpdatedAt    string `json:"updated_at"`    // 更新时间
}

type TaskVisualizationResponse struct {
	Tid          string           `json:"tid"`           // 任务唯一标识
	Name         string           `json:"name"`          // 任务名称
	Types        string           `json:"types"`         // 任务类型
	Status       string           `json:"status"`        // 任务状态
	CurrentState string           `json:"current_state"` // 当前状态机
	TotalSteps   int64            `json:"total_steps"`   // 总步骤
	CurrentStep  int64            `json:"current_step"`  // 当前步骤
	Plans        []TaskPlanDetail `json:"plans"`         // 任务计划详情
	CreatedAt    string           `json:"created_at"`    // 创建时间
	UpdatedAt    string           `json:"updated_at"`    // 更新时间
}

type URLRequest struct {
	URL string `json:"url"` // URL链接
}

type URLResponse struct {
	Tag         []string `json:"tag"`         // 标签
	Title       string   `json:"title"`       // 标题
	Description string   `json:"description"` // 描述
	Link        string   `json:"link"`        // 链接
}

type UpdateModelRequest struct {
	Id            int64    `json:"id"`              // 主键
	BaseUrl       string   `json:"base_url"`        // 基础URL
	Config        string   `json:"config"`          // 配置信息
	Type          string   `json:"type"`            // 类型
	ModelName     string   `json:"model_name"`      // 模型名称
	ModelRealName string   `json:"model_real_name"` // 模型真实名称
	Status        string   `json:"status"`          // 状态
	Tag           []string `json:"tag"`             // 标签
}

type UpdateResourceRequest struct {
	Id      int64    `json:"id"`       // 主键
	URL     string   `json:"url"`      // URL链接
	Title   string   `json:"title"`    // 标题
	Content string   `json:"content"`  // 内容
	Type    string   `json:"type"`     // 类型
	TagUids []string `json:"tag_uids"` // 标签
}

type UpdateTagRequest struct {
	Uid         string `json:"uid,optional"` // 标签唯一标识
	Name        string `json:"name"`         // 标签名称
	Description string `json:"description"`  // 标签描述
	Color       string `json:"color"`        // 标签颜色
	Icon        string `json:"icon"`         // 标签图标
}

type UpdateTagResponse struct {
	Id          int64  `json:"id"`          // 主键ID
	Uid         string `json:"uid"`         // 标签唯一标识
	Name        string `json:"name"`        // 标签名称
	Description string `json:"description"` // 标签描述
	Color       string `json:"color"`       // 标签颜色
	Icon        string `json:"icon"`        // 标签图标
	CreatedAt   string `json:"created_at"`  // 创建时间
	UpdatedAt   string `json:"updated_at"`  // 更新时间
}

type UpdateTaskRequest struct {
	Tid          string `json:"tid"`                    // 任务唯一标识
	Name         string `json:"name,optional"`          // 任务名称
	Status       string `json:"status,optional"`        // 任务状态
	CurrentState string `json:"current_state,optional"` // 当前状态机
	CurrentStep  int64  `json:"current_step,optional"`  // 当前步骤
	Result       string `json:"result,optional"`        // 任务结果
	RetryCount   int64  `json:"retry_count,optional"`   // 重试次数
	Error        string `json:"error,optional"`         // 任务错误
	Extend       string `json:"extend,optional"`        // 扩展字段
}

type UpdateTaskResponse struct {
	Id           int64  `json:"id"`            // 主键ID
	Tid          string `json:"tid"`           // 任务唯一标识
	Name         string `json:"name"`          // 任务名称
	Types        string `json:"types"`         // 任务类型
	Status       string `json:"status"`        // 任务状态
	CurrentState string `json:"current_state"` // 当前状态机
	TotalSteps   int64  `json:"total_steps"`   // 总步骤
	CurrentStep  int64  `json:"current_step"`  // 当前步骤
	RetryCount   int64  `json:"retry_count"`   // 重试次数
	Params       string `json:"params"`        // 任务参数
	Result       string `json:"result"`        // 任务结果
	Duration     int64  `json:"duration"`      // 任务耗时
	Error        string `json:"error"`         // 任务错误
	Extend       string `json:"extend"`        // 扩展字段
	CreatedAt    string `json:"created_at"`    // 创建时间
	UpdatedAt    string `json:"updated_at"`    // 更新时间
}
