// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	api "github.com/XXueTu/wise/internal/handler/api"
	"github.com/XXueTu/wise/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// API基础
				Method:  http.MethodPost,
				Path:    "/api/base",
				Handler: api.BaseHandler(serverCtx),
			},
			{
				// URL链接识别
				Method:  http.MethodPost,
				Path:    "/api/url",
				Handler: api.UrlHandler(serverCtx),
			},
		},
		rest.WithPrefix("/wise"),
	)
}
